# Generated by Django 3.2.7 on 2021-09-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contect',
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.CharField(default=True, max_length=15),
        ),
    ]
